// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
CANJaguar* RobotMap::driveTrainCANJaguar1 = NULL;
CANJaguar* RobotMap::driveTrainCANJaguar2 = NULL;
RobotDrive* RobotMap::driveTrainRobotDrive = NULL;
CANJaguar* RobotMap::shootermainShooter = NULL;
CANJaguar* RobotMap::shootersupportShooter = NULL;
Gyro* RobotMap::angleCheckWithGyroGyro1 = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	driveTrainCANJaguar1 = new CANJaguar(6);
	
	
	driveTrainCANJaguar2 = new CANJaguar(9);
	
	
	driveTrainRobotDrive = new RobotDrive(driveTrainCANJaguar1, driveTrainCANJaguar2);
	
	driveTrainRobotDrive->SetSafetyEnabled(true);
        driveTrainRobotDrive->SetExpiration(0.1);
        driveTrainRobotDrive->SetSensitivity(0.5);
        driveTrainRobotDrive->SetMaxOutput(1.0);
        
	shootermainShooter = new CANJaguar(5);
	
	
	shootersupportShooter = new CANJaguar(7);
	
	
	angleCheckWithGyroGyro1 = new Gyro(1, 1);
	lw->AddSensor("AngleCheckWithGyro", "Gyro 1", angleCheckWithGyroGyro1);
	angleCheckWithGyroGyro1->SetSensitivity(1.25);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
