// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::climberSpeedController1 = NULL;
SpeedController* RobotMap::climberSpeedController2 = NULL;
CANJaguar* RobotMap::climberLeftCIM = NULL;
CANJaguar* RobotMap::climberRightCIM = NULL;
CANJaguar* RobotMap::driveTrainCANJaguar1 = NULL;
CANJaguar* RobotMap::driveTrainCANJaguar2 = NULL;
RobotDrive* RobotMap::driveTrainRobotDrive = NULL;
SpeedController* RobotMap::collectorCollectorMotor = NULL;
AnalogChannel* RobotMap::collectorHowManyDisks = NULL;
DigitalInput* RobotMap::collectorDiskOnTheBed = NULL;
AnalogChannel* RobotMap::collectorUpsideDown = NULL;
CANJaguar* RobotMap::shootermainShooter = NULL;
CANJaguar* RobotMap::shootersupportShooter = NULL;
Encoder* RobotMap::shooterWheelCounter = NULL;
CANJaguar* RobotMap::shooterAngleElevationJag = NULL;
DigitalInput* RobotMap::shooterLightSensor = NULL;
Gyro* RobotMap::angleCheckWithGyroGyro1 = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	climberSpeedController1 = new Victor(1, 1);
	lw->AddActuator("Climber", "Speed Controller 1", (Victor*) climberSpeedController1);
	
	climberSpeedController2 = new Victor(1, 2);
	lw->AddActuator("Climber", "Speed Controller 2", (Victor*) climberSpeedController2);
	
	climberLeftCIM = new CANJaguar(2);
	
	
	climberRightCIM = new CANJaguar(3);
	
	
	driveTrainCANJaguar1 = new CANJaguar(6);
	
	
	driveTrainCANJaguar2 = new CANJaguar(9);
	
	
	driveTrainRobotDrive = new RobotDrive(driveTrainCANJaguar1, driveTrainCANJaguar2);
	
	driveTrainRobotDrive->SetSafetyEnabled(false);
        driveTrainRobotDrive->SetExpiration(0.1);
        driveTrainRobotDrive->SetSensitivity(0.5);
        driveTrainRobotDrive->SetMaxOutput(1.0);
        
	collectorCollectorMotor = new Victor(1, 3);
	lw->AddActuator("Collector", "CollectorMotor", (Victor*) collectorCollectorMotor);
	
	collectorHowManyDisks = new AnalogChannel(1, 2);
	lw->AddSensor("Collector", "HowManyDisks", collectorHowManyDisks);
	
	collectorDiskOnTheBed = new DigitalInput(1, 3);
	lw->AddSensor("Collector", "DiskOnTheBed", collectorDiskOnTheBed);
	
	collectorUpsideDown = new AnalogChannel(1, 3);
	lw->AddSensor("Collector", "UpsideDown", collectorUpsideDown);
	
	shootermainShooter = new CANJaguar(5);
	
	
	shootersupportShooter = new CANJaguar(7);
	
	
	shooterWheelCounter = new Encoder(1, 1, 1, 2, false, Encoder::k4X);
	lw->AddSensor("Shooter", "WheelCounter", shooterWheelCounter);
	shooterWheelCounter->SetDistancePerPulse(1.0);
        shooterWheelCounter->SetPIDSourceParameter(Encoder::kRate);
        shooterWheelCounter->Start();
	shooterAngleElevationJag = new CANJaguar(4);
	
	
	shooterLightSensor = new DigitalInput(1, 4);
	lw->AddSensor("Shooter", "LightSensor", shooterLightSensor);
	
	angleCheckWithGyroGyro1 = new Gyro(1, 1);
	lw->AddSensor("AngleCheckWithGyro", "Gyro 1", angleCheckWithGyroGyro1);
	angleCheckWithGyroGyro1->SetSensitivity(0.007);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
