// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef CLIMBER_H
#define CLIMBER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Climber: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	float climberSpeed;
	float MagneticValue1;
	float MagneticValue2;
	float wtf;
	float whoops;
	float leftCIMSpeed;
	float rightCIMSpeed;
	float CIMVoltsLeft;
	float CIMVoltsRight;
	float armVoltsLeft;
	float armVoltsRight;
	//float climberSpeed1;
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* speedController1;
	SpeedController* speedController2;
	CANJaguar* leftCIM;
	CANJaguar* rightCIM;
	AnalogChannel* magneticEncoder1;
	AnalogChannel* magneticencoder2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Climber();
	void InitDefaultCommand();
	void SetSpeed(float inSpeed2);
	float GetSpeed();
	void GetStuff();
	void SetArms(float inspeed3);
	float GetArms();
};
#endif
