// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "DriveTrain.h"
#include "../Robotmap.h"
#include "../Commands/ArcadeDrive.h"
#include "../OI.h"
#include "../Commands/DriveEncoders.h"
extern float XValue2;
extern float YValue2;
DriveTrain::DriveTrain() : Subsystem("DriveTrain") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	cANJaguar1 = RobotMap::driveTrainCANJaguar1;
	cANJaguar2 = RobotMap::driveTrainCANJaguar2;
	robotDrive = RobotMap::driveTrainRobotDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void DriveTrain::InitDefaultCommand() {
	//cANJaguar1->ChangeControlMode(CANJaguar::kPosition);
	cANJaguar1->SetPositionReference(CANJaguar::kPosRef_QuadEncoder);
	cANJaguar1->ConfigEncoderCodesPerRev(360);
	cANJaguar1->EnableControl();
	cANJaguar2->SetPositionReference(CANJaguar::kPosRef_QuadEncoder);
	cANJaguar2->ConfigEncoderCodesPerRev(360);
	cANJaguar2->EnableControl();
	printf ("the configuration for DRIVE is complete\n");
	//SetDefaultCommand(new DriveEncoders());
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new ArcadeDrive());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
void DriveTrain::Drive_with_joy( Joystick *stick ) {
	
	robotDrive->ArcadeDrive( stick );
}
void DriveTrain::Drive_with_abandon( void ) {
	float moveValue = (float)(rand())/(float)RAND_MAX;
	float rotateValue = 0.0;
	std::string keystring = "Arcade Speed";
	robotDrive->ArcadeDrive( moveValue, rotateValue );
	SmartDashboard::PutNumber( keystring, (double)moveValue);
}
void DriveTrain::Halt_drive( void ) {	
	robotDrive->ArcadeDrive( 0.0, 0.0 );
}
void DriveTrain::ReportEncoders() {
	//cANJaguar1->GetControlMode();
	float encoder1 = cANJaguar1->GetPosition();
	float encoder2 = cANJaguar2->GetPosition();
	float voltage1 = cANJaguar1->GetOutputVoltage();
	float voltage2 = cANJaguar2->GetOutputVoltage();
	//printf ("drive encoder %f\n", encoder1);
	SmartDashboard::PutNumber( "Drive Encoder 1", (double)encoder1 );
	SmartDashboard::PutNumber( "Drive Encoder 2", (double)encoder2 );
	SmartDashboard::PutNumber( "Left CIM Voltage", (double)voltage1 );
	SmartDashboard::PutNumber( "Right CIM Voltage", (double)voltage2 );
}
/*void DriveTrain::ConfigureJaguarEncoder(CANJaguar* cANJaguar1, CANJaguar* cANJaguar2){
	cANJaguar1->ChangeControlMode(CANJaguar::kSpeed);
	cANJaguar1->SetSpeedReference(CANJaguar::kSpeedRef_Encoder);
	cANJaguar1->ConfigEncoderCodesPerRev(360);	//maybe 360
	cANJaguar2->ChangeControlMode(CANJaguar::kSpeed);
	cANJaguar2->SetSpeedReference(CANJaguar::kSpeedRef_Encoder);
	cANJaguar2->ConfigEncoderCodesPerRev(360);	//maybe 360
	cANJaguar1->EnableControl();
	cANJaguar2->EnableControl();
}
void Shooter::SetPID(double P, double I, double D){
	printf("Setting P:\t%f\nI:\t%f\nD:\t%f\n", P, I, D);
	frontJag->SetPID(P, I, D);
	backJag->SetPID(P, I, D);
}
*/
